# Generated by Django 4.1.7 on 2023-11-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="follows",
        ),
        migrations.AddField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to="profiles.profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="O",
                max_length=20,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_handle",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="twitter handle"
            ),
        ),
    ]
